name: Deploy To Staging Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          key: ${{secrets.SERVER_SSH_KEY}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            cd ts-api-with-test-js-hng-st-2
            git pull https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/JC-Coder/ts-api-with-test-js-hng-st-2.git
            export APP_NAME="${{secrets.APP_NAME}}"
            export APP_PORT="${{secrets.APP_PORT}}"
            export APP_ENV="${{secrets.APP_ENV}}"
            export JWT_SECRET="${{secrets.JWT_SECRET}}"
            export DB_HOST="${{secrets.DB_HOST}}"
            export DB_PORT="${{secrets.DB_PORT}}"
            export DB_USERNAME="${{secrets.DB_USERNAME}}"
            export DB_PASSWORD="${{secrets.DB_PASSWORD}}"
            export DB_NAME="${{secrets.DB_NAME}}"
            yarn
            yarn build
            yarn start:prod
            echo "Deployment to Staging Server Completed"
